---
title: "mtcars-JuliaS-mtcars"
author: "Ravi Hela"
date: "29/09/2019"
output: html_document
---

```{r}
library("tidyverse")
library(readxl)

```


```{r setup, include=FALSE}
cars2018 <- read_csv("Data_Science/supervised-ML-case-studies-course-master/data/cars2018.csv")

glimpse(cars2018)

ggplot(cars2018, aes(x = MPG)) +
    geom_histogram(bins = 25) +
    labs(x = "Fuel efficiency (mpg)",
         y = "Number of cars")


```

```{r}
# Deselect the 2 columns to create cars_vars
car_vars <- cars2018 %>%
    select(-Model, -`Model Index`)


fit_all <- lm(MPG ~ ., data = car_vars)
summary(fit_all)


```


```{r}
library(rsample)

car_split <- car_vars %>%
    initial_split(prop = 0.8,
                  strata = "Aspiration")

car_training <- training(car_split)
car_testing <- testing(car_split)

```

```{r}
library(caret)

fit_lm <- train(log(MPG) ~ ., 
                method = "lm", 
                data = car_training,
                trControl = trainControl(method = "none"))

```


```{r}
set.seed(1234)
car_split <- car_vars %>%
    initial_split(prop = 0.8, strata = "Transmission")

car_train <- training(car_split)
car_test <- testing(car_split)
```


```{r, linear model}
fit_lm <- train(log(MPG) ~ ., 
                method = "lm", 
                data = car_train,
                trControl = trainControl(method = "none"))

# Print the model object
fit_lm
```


```{r}
library(randomForest)

# Train a random forest model
fit_rf <- train(log(MPG) ~ ., 
                method = "rf", 
                data = car_train,
                trControl = trainControl(method = "none"))

# Print the model object
fit_rf
```



```{r}
# Load yardstick
library(yardstick)

# Create the new columns
results <- car_train %>%
    mutate(`Linear regression` = predict(fit_lm, car_train),
           `Random forest` = predict(fit_rf, car_train))

# Evaluate the performance
metrics(results, truth = MPG, estimate = `Linear regression`)
metrics(results, truth = MPG, estimate = `Random forest`)


```


```{r}
results <- car_test %>%
    mutate(`Linear regression` = predict(fit_lm, car_test),
           `Random forest` = predict(fit_rf, car_test))

# Evaluate the performance
metrics(results, truth = MPG, estimate = `Linear regression`)
metrics(results, truth = MPG, estimate = `Random forest`)

```

```{r}
cars_lm_bt <- train(log(MPG) ~ ., 
                    method = "lm", 
                    data = car_train,
                    trControl = trainControl(method = "boot"))

cars_rf_bt <- train(log(MPG) ~ ., 
                    method = "rf", 
                    data = car_train,
                    trControl = trainControl(method = "boot"))
                   
# Quick look at the models
cars_lm_bt
cars_rf_bt
```


```{r}
results <- car_test %>%
    mutate(`Linear regression` = predict(cars_lm_bt, car_test),
           `Random forest` = predict(cars_rf_bt, car_test))

metrics(results, truth = MPG, estimate = `Linear regression`)
metrics(results, truth = MPG, estimate = `Random forest`)
```


```{r}
results %>%
    gather(Method, Result, `Linear regression`:`Random forest`) %>%
    ggplot(aes(log(MPG), Result, color = Method)) +
    geom_point(size = 1.5, alpha = 0.5) +
    facet_wrap(~Method) +
    geom_abline(lty = 2, color = "gray50") +
    geom_smooth(method = "lm")

```

